name: CI/CD workflow for Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: Redes-Chat-Protocolo-XMPP
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=javim7_Redes-Chat-Protocolo-XMPP_AZKwKqQiWEa_O596rqxc
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
